import type { Employee } from "./employee-types"

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    name: "Rajesh Kumar",
    employeeId: "EMP001",
    phone: "+91 98765 43210",
    email: "rajesh.kumar@company.com",
    gender: "Male",
    role: "Senior Developer",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "emp-002",
    name: "Priya Sharma",
    employeeId: "EMP002",
    phone: "+91 98765 43211",
    email: "priya.sharma@company.com",
    gender: "Female",
    role: "Team Leader",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
  },
  {
    id: "emp-003",
    name: "Amit Patel",
    employeeId: "EMP003",
    phone: "+91 98765 43212",
    email: "amit.patel@company.com",
    gender: "Male",
    role: "Junior Developer",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
  },
  {
    id: "emp-004",
    name: "Sneha Reddy",
    employeeId: "EMP004",
    phone: "+91 98765 43213",
    email: "sneha.reddy@company.com",
    gender: "Female",
    role: "UI/UX Designer",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
  },
  {
    id: "emp-005",
    name: "Vikram Singh",
    employeeId: "EMP005",
    phone: "+91 98765 43214",
    email: "vikram.singh@company.com",
    gender: "Male",
    role: "QA Engineer",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
  },
  {
    id: "emp-006",
    name: "Ananya Iyer",
    employeeId: "EMP006",
    phone: "+91 98765 43215",
    email: "ananya.iyer@company.com",
    gender: "Female",
    role: "Project Manager",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "emp-007",
    name: "Karan Mehta",
    employeeId: "EMP007",
    phone: "+91 98765 43216",
    email: "karan.mehta@company.com",
    gender: "Male",
    role: "DevOps Engineer",
    status: "Inactive",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    id: "emp-008",
    name: "Neha Gupta",
    employeeId: "EMP008",
    phone: "+91 98765 43217",
    email: "neha.gupta@company.com",
    gender: "Female",
    role: "Business Analyst",
    status: "Active",
    regularShifts: [],
    overtimeShifts: [],
    salaryConfig: {
      frequency: "By Month",
      workdayPolicy: "Exclude Sundays",
    },
    createdAt: "2024-01-30",
    updatedAt: "2024-01-30",
  },
]
